### ISSUE TITLE
Switching to PCOV?

### ISSUE THREAD

**Issue by alouini333** [fossbarrow/laravel-clean-docker#2]
While Xdebug works perfectly with PHPUnit as a coverage driver. It is very slow comparing to [PCov](https://github.com/krakjoe/pcov)

You can find a comparaision [here](https://kizu514.com/blog/pcov-is-better-than-phpdbg-and-xdebug-for-code-coverage/)

I'm going to create a pull request to apply the changes required to migrate from Xdebug to Pcov
This will optimize the memory and time of tests when developing a Laravel application

**Comment by PatricNox** [comment]
Hello @alouini333 !

Xdebug is an extension for PHP to assist with debugging and development, not a coverage tool.

Is it phpcs you mean? 

If so, then we'd like to keep the template to use phpcs by default due to the [Laravel phpcs code standard ruleset.](https://github.com/fossbarrow/laravel-phpcs)

Thank you for your idea, however!
